#!/usr/bin/env bash
# WARNING: this script will destroy data on the selected directory.

set -euo pipefail
trap 'var=s; s=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

REPO_URL=git@github.com:lemuelroberto/dotfiles.git

# Exit if a target directory was not provided
if [ "$#" -lt 1 ]; then
  echo >&2 "error: you must provide a non empty parameter with the target directory"
  exit 1
fi

# Get full path of target directory
declare target
if [ "$1" == "." ]; then
    target="$(pwd)"
elif [ "$1" == ".." ]; then
    target="$(dirname "$(pwd)")"
else
    target="$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
fi

# Make sure the user wants to remove all files on target
echo "Will remove all files on ${target}"
read -p "Are you sure? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Exiting without setting up dotfiles"
    exit 1
fi

cd "${target}" || exit 1

rm -rf ./.??* ./* # Remove all files, including the hidden ones

gitbare() {
    git --git-dir="${target}"/dotfiles/ --work-tree="${target}" "$@"
}

# Setup bare repository
git init --bare "${target}"/dotfiles
gitbare remote add -f origin $REPO_URL
gitbare fetch origin develop:develop
gitbare checkout develop
