#!/usr/bin/env bash
# WARNING: this script will destroy all data on the $HOME directory.

set -euo pipefail
trap 'var=s; s=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# Accepts REPO_URL in the environment or use default value
REPO_URL="${REPO_URL:-git@github.com:lemuelroberto/dotfiles.git}"

# Make sure the user wants to remove all files on target
# WARNING: Reading user input when the script is piped to shell may result in
# unexpected behaivour.
# It's safer to execute bash <(cat install) than cat install | bash.
# Read discussion at stackoverflow to understand why we need read from /dev/tty.
# https://stackoverflow.com/a/20149981/5111444
echo "Will remove all files on $HOME"
read -p "Are you sure? " -n 1 -r < /dev/tty
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Exiting without setting up dotfiles"
    exit 1
fi

cd "$HOME" || exit 1

rm -rf ./.??* ./* # Remove all files, including the hidden ones

# Setup repository
git init
git remote add -f origin $REPO_URL
git fetch origin develop:develop
git checkout develop
