#!/bin/bash

# Easier navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias -- -="cd -"

# ls shortcuts
alias ls="ls --group-directories-first"
alias ll="ls -la"

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
	alias ls="ls --color=auto"
	alias grep="grep --color=auto"
	alias fgrep="fgrep --color=auto"
	alias egrep="egrep --color=auto"
fi

# Edit hosts
alias hosts="sudo vim /etc/hosts"

# git shortcuts
alias st="git status"
alias gd="git diff"
alias gl="git log"

# Copy working directory
alias cpwd="pwd | tr -d "\r\n" | xclip -selection clipboard"
