#!/bin/bash

# Define the workspace directory
export WORKSPACE=/$HOME/workspace

# Define the repositories directory
export REPOSITORIES=$HOME/repositories

# Define default text editor
export EDITOR=vim

# Define text window's capabilities
export TERM=xterm-256color

# Enable BuildKit for faster Docker builds
export DOCKER_BUILDKIT=1

# Config gpg-agent
GPG_TTY=$(tty)
export GPG_TTY
