#!/bin/bash

# Define go path
export GOPATH=${HOME}/.go

# Add go/bin to path
export GOBIN=${GOPATH}/bin
export PATH=/usr/local/go/bin:${GOBIN}:${PATH}

# Add ~/bin to path
export PATH=${HOME}/bin:${PATH}

# Add ~/.screenlayout to path
export PATH=${HOME}/.screenlayout:${PATH}
